#!/usr/bin/env bash
# Function to display usage information
usage() {
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
}

# Check if an argument is provided
if [ "$#" -ne 1 ]; then
    usage
fi

# Extract the IP address from the arguments
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"

exit 0
