#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 13 ]
do
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$hour:$minute"
		(( $minute++ ))
	done
	(( $hour++ ))

done | hour -n 70
	
